#!/bin/sh

if [ $# -eq 0 ] || [ "$1" == "-h" ] || [ "$1" == "-help" ] || [ "$1" == "--help" ]; then
    echo "Usage: ./"$(basename "$0")" <date>"
    echo "Example: ./"$(basename "$0")" 20170228"
    echo "<date> = PhEDEx date in the following format: YYYYMMDD."
    exit 0
fi

# Treat first argument as date. 
# Date will be validated in actual scripts below.
date=$1

# Get current script's absolute path
scriptpath="$( cd "$(dirname "$0")" ; pwd -P )"

$scriptpath/report_averages/aggregate_averages &
$scriptpath/report_campaigns/aggregate $date &
$scriptpath/report_leftovers/aggregate_leftovers $date &
$scriptpath/report_tiers/aggregate $date &
wait
